//Forr Testing
public class accountContactCreateUpdate {
    
    public static void accCret(){
        Account acc = new Account();
		acc.Name = 'Prathmesh';
        acc.BillingCity ='Nagpur';
        insert acc;
    } 
    
     public static void accUpdate(){
        Account acc = new Account();
		acc.Name = 'Prathmesh';
        acc.BillingCity ='Nagpur';
        insert acc;
    } 
     public static void conCreat(){
        Account acc = new Account();
		acc.Name = 'Prathmesh';
        acc.BillingCity ='Nagpur';
        insert acc;
    } 
     public static void conUpdate(){
        Account acc = new Account();
		acc.Name = 'Prathmesh';
        acc.BillingCity ='Nagpur';
        insert acc;
    } 

}